version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  auth:
    build: ./auth
    container_name: auth_service
    ports:
      - "5000:5000"
    depends_on:
      - auth_db

  user:
    build: ./user
    container_name: user_service
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
      - user_db

  product:
    build: ./product
    container_name: product_service
    ports:
      - "5002:5002"
    depends_on:
      - product_db

  auth_db:
    image: mysql:latest
    container_name: auth_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_auth
    ports:
      - "3308:3306"   
    volumes:
      - ./auth/init:/docker-entrypoint-initdb.d

  user_db:
    image: mysql:latest
    container_name: user_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_user
    ports:
      - "3307:3306"
    volumes:
      - ./user/init:/docker-entrypoint-initdb.d
      
  product_db:
    image: mysql:latest
    container_name: product_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_product
    ports:
      - "3309:3306"
    volumes:
      - ./product/init:/docker-entrypoint-initdb.d

  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    depends_on:
      - auth
      - user
