server:
  http_listen_port: 3100

ingester:
  wal:
    enabled: true
    dir: /loki/wal

storage_config:
  boltdb_shipper:
    directory: /loki/chunks
    retention_policy: 30d
  boltdb:
    directory: /loki/indexes

schema_config:
  configs:
    - from: 2021-01-01
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  max_query_length: 1h

chunk_target_size: 1048576
